ALTER TABLE IF EXISTS "Livestocks"
    ADD COLUMN IF NOT EXISTS "CreatedBy" VARCHAR(128) NOT NULL DEFAULT '';

ALTER TABLE IF EXISTS "HealthRecords"
    ADD COLUMN IF NOT EXISTS "CreatedBy" VARCHAR(128) NOT NULL DEFAULT '';

ALTER TABLE IF EXISTS "BreedingCycles"
    ADD COLUMN IF NOT EXISTS "CreatedBy" VARCHAR(128) NOT NULL DEFAULT '';