ALTER TABLE IF EXISTS "Dairies"
    ADD COLUMN IF NOT EXISTS "CreatedBy" VARCHAR(128) NOT NULL DEFAULT '';

ALTER TABLE IF EXISTS "FeedConsumptions"
    ADD COLUMN IF NOT EXISTS "CreatedBy" VARCHAR(128) NOT NULL DEFAULT '';