ALTER TABLE IF EXISTS "Incomes"
    ADD COLUMN IF NOT EXISTS "CreatedBy" VARCHAR(128) NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS "Expenses"
    ADD COLUMN IF NOT EXISTS "CreatedBy" VARCHAR(128) NOT NULL DEFAULT '';
